name: Spec Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    types: [opened, edited]

jobs:
  spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ github.event_name }}-${{ hashFiles('**/package-lock.json') }}
          restore-key: ${{ runner.os }}-node-${{ github.event_name }}-
      - run: npm i
      - run: npm run test
